### PR TITLE
Fix for issue #799: Chrome 56 preventDefault inside passive event listener

### PR DESCRIPTION
**Pull request by Tolc**
#799
Fix for issue with Chrome 56 preventDefault inside passive event listener

### CODE REVIEW

**Comment by JuanGongora** [comment]
Thanks! That did the trick!

**Comment by f0nt4** [comment]
Thanks!

**Comment by wixaw** [comment]
Merci thomas !

**Comment by sarahtheblue** [comment]
thanks!

**Comment by elzix** [comment]
+1

**Comment by Stev3nsen** [comment]
@Tolc Good job

Why is there no progress with the merge? I think quit a lot of people waiting for this fix.

**Comment by wangshuai330508** [comment]
thanks!!!!!!

**Comment by f0nt4** [comment]
> @Tolc Good job
> 
> Why is there no progress with the merge? I think quit a lot of people waiting for this fix.

That's because @inuyaksa already hasn't done anything on Github for over a year.

**Comment by PowerMostafa** [comment]
Thanks alot

**Comment by victorlucss** [comment]
Thank you!

**Comment by zdimaz** [comment]
[Chrome] Unable to preventDefault inside passive event listener due to target being treated as passive.

Bugs not fix ((((
CRY CRY CRY (
Help bro pls

**Comment by halbano** [comment]
We are experiencing the same issue. Should we apply the fix on our own? Are you planning to merge the change? Thanks in advance.

**Pull request merged**
