### PR TITLE
Update jquery.nicescroll.js

### PR DESCRIPTION
**Pull request by TNKSoftware**
Ignore scrolling when action is multi-touched.

### CODE REVIEW

**Comment by dandamudi** [comment]
@inuyaksa ,

i am using nicescroll.js file in my (https secured site), one of html container i used below code, 
//$(document).ready(function () {
  
//            $(".scroll-view").niceScroll({
//                touchbehavior: true,
//                cursorcolor: "rgba(84, 64,82, 0.35)"
//            });
//});

but in IE , when i moved to cursor to on container, iodesn't show up, but it should be openhand cursor, i guess because of it calls to "//mail.google.com/mail/images/2/openhand.cur"
my site won't allow display the public site content.

can you please give me any solution for this , i spent 2 days on this issue.

**Comment by PlippiePlop** [comment]
copy the openhand.cur to your local (website) directory and point to that in the source.

**Comment by dandamudi** [comment]
@ thanks for Quick response,
i tried to copy on my local, but it saved to filetype has  .cur file, is there way to get  .png image?

**Comment by dandamudi** [comment]
@PlippiePlop i replace below code in jquery.nicescroll.js
"url(http://www.google.com/intl/en_ALL/mapfiles/openhand.cur),n-resize" 

with "url(Img/openhand.png),n-resize"   Img is my local folder in my solution.
still not working IE,  did i any wrong?

**Comment by PlippiePlop** [comment]
It wont work with a png. You need to have .cur file for custom mouse cursor. Also add absolute path to the file.

**Comment by dandamudi** [comment]
thanks @PlippiePlop , i changed to .cur, now it's working fine in IE also

**Pull request closed without merging**
